version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis-cli
      - redis-server

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blocked_ips
    volumes:
      - 'pg_data2:/var/lib/postgresql/data/pgdata'
    ports:
      - '5445:5432'

  redis-server:
    image: redis
    ports:
      - '6379:6379'

  redis-cli:
    image: redis

volumes:
  pg_data2: